### ISSUE TITLE
Create local repository / push to local repo

### ISSUE THREAD

**Issue by armanossiloko** [stackblitz-labs/bolt.diy#1447]
As it currently stands, I have not figure out or found a way to actually get `bolt.diy` to create repositories locally on my disk so that they can be browsable (aka so that I can open a repo locally in VS Code and then see what has changed and decide what I want to push to a remote repository myself).

Under the premise that this truly is not possible currently (as I may have overlooked something), I would like to request a feature to be able to create repositories locally on my disk and then decide what gets pushed manually.

**Comment by zeneiltongpdev** [comment]
> As it currently stands, I have not figure out or found a way to actually get `bolt.diy` to create repositories locally on my disk so that they can be browsable (aka so that I can open a repo locally in VS Code and then see what has changed and decide what I want to push to a remote repository myself).
> 
> Under the premise that this truly is not possible currently (as I may have overlooked something), I would like to request a feature to be able to create repositories locally on my disk and then decide what gets pushed manually.

@armanossiloko Yes bro, you can create your repository manually in your local directory and then import your folder into Bolt.diy. After your changes are made or your codes are built, use the `sync files` button, and everything will be ready to be pushed to your remote repository.

In my case, I just deployed the application to the web following @leex279 instructions, so I can now do this automatically.

Good luck to you ⚡

![Image](https://github.com/user-attachments/assets/8af663c9-3820-4ce2-8d89-96d63d386790)
![Image](https://github.com/user-attachments/assets/cf3bd181-8b39-4758-8efb-aa37518079ac)

**Comment by armanossiloko** [comment]
> > As it currently stands, I have not figure out or found a way to actually get `bolt.diy` to create repositories locally on my disk so that they can be browsable (aka so that I can open a repo locally in VS Code and then see what has changed and decide what I want to push to a remote repository myself).
> > Under the premise that this truly is not possible currently (as I may have overlooked something), I would like to request a feature to be able to create repositories locally on my disk and then decide what gets pushed manually.
> 
> [@armanossiloko](https://github.com/armanossiloko) Yes bro, you can create your repository manually in your local directory and then import your folder into Bolt.diy. After your changes are made or your codes are built, use the `Sync Files` button, and everything will be ready to be pushed to your remote repository.
> 
> In my case, I just deployed the application to the web following [@leex279](https://github.com/leex279) instructions, so I can now do this automatically.
> 
> Good luck to you ⚡
> 
> ![Image](https://github.com/user-attachments/assets/8af663c9-3820-4ce2-8d89-96d63d386790) ![Image](https://github.com/user-attachments/assets/cf3bd181-8b39-4758-8efb-aa37518079ac)

Do you know if I need to configure anything additionally beside just importing the folder?

I imported the folder and and tried out a sample and it worked ok, but after it finishes its job and makes its changes, when I click on `Sync files`, I get an error toast

![Image](https://github.com/user-attachments/assets/dff33dd2-c485-4b75-8be2-64c799c549e5)

The only thing visible seems to be a console error stating that `window.showDirectoryPicker is not a function`.

![Image](https://github.com/user-attachments/assets/ca7fb4d9-fdb2-42c8-acf8-d9b97c544854)

**Comment by leex279** [comment]
@armanossiloko any ad-blockers or other extensions in your browser? justed myself again and worked without any errors.

**Comment by zeneiltongpdev** [comment]
> > > No momento, não descobri ou encontrei uma maneira de realmente `bolt.diy`criar repositórios localmente no meu disco para que eles possam ser navegados (também conhecido como para que eu possa abrir um repositório localmente no VS Code e então ver o que mudou e decidir o que eu quero enviar para um repositório remoto sozinho). 
> > > Sob a premissa de que isso realmente não é possível atualmente (pois posso ter esquecido de algo), gostaria de solicitar um recurso para poder criar repositórios localmente no meu disco e então decidir o que será enviado manualmente.
> > 
> > 
> > [@armanossiloko](https://github.com/armanossiloko) Sim, mano, você pode criar seu repositório manualmente no seu diretório local e então importar sua pasta para o Bolt.diy. Depois que suas alterações forem feitas ou seus códigos forem construídos, use o `Sync Files`botão, e tudo estará pronto para ser enviado para seu repositório remoto.
> > No meu caso, acabei de implantar o aplicativo na web seguindo as instruções [do @leex279](https://github.com/leex279) , então agora posso fazer isso automaticamente.
> > Boa sorte para você ⚡
> > ![Image](https://github.com/user-attachments/assets/8af663c9-3820-4ce2-8d89-96d63d386790) ![Imagem](https://private-user-images.githubusercontent.com/8356174/419138230-cf3bd181-8b39-4758-8efb-aa37518079ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDExMTcyNTAsIm5iZiI6MTc0MTExNjk1MCwicGF0aCI6Ii84MzU2MTc0LzQxOTEzODIzMC1jZjNiZDE4MS04YjM5LTQ3NTgtOGVmYi1hYTM3NTE4MDc5YWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMDRUMTkzNTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODNiNWY3MjlmODQ1YTIzYTU4ZTY0NDhhZWRhOGY4NDI2NzE0NWVmNmY1MjRhNmQ4NmViYTYyM2JmZGRkZDZjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.gmyg4yOCBQn-RJjp0sCBdf0tN6i0fmRUKigtEjm2YGs)
> 
> Você sabe se preciso configurar algo adicional além de apenas importar a pasta?
> 
> Importei a pasta e testei um exemplo e funcionou bem, mas depois que ele termina seu trabalho e faz suas alterações, quando clico em `Sync files`, recebo um erro toast
> 
> ![Image](https://github.com/user-attachments/assets/dff33dd2-c485-4b75-8be2-64c799c549e5)
> 
> A única coisa visível parece ser um erro de console informando que `window.showDirectoryPicker is not a function`.
> 
> ![Image](https://github.com/user-attachments/assets/ca7fb4d9-fdb2-42c8-acf8-d9b97c544854)

##

@armanossiloko I understand your problem friend, but try [Leex's](https://github.com/stackblitz-labs/bolt.diy/issues/1447#issuecomment-2698700066) suggestion, if it doesn't solve it,You can also try using [Google Chrome Canary](https://www.google.com/intl/en/chrome/canary/), an excellent browser option for development testing.

**Comment by armanossiloko** [comment]
> [@armanossiloko](https://github.com/armanossiloko) any ad-blockers or other extensions in your browser? justed myself again and worked without any errors.

I had Brave Shields enabled and a few extensions. I went on and disabled them, but still facing the same issue.
Funnily enough, though, I seem to have been able to do the `Sync files` with Microsoft Edge.
I am not sure why it's not working for Brave even when Brave Shields and all extensions are disabled.

**Comment by armanossiloko** [comment]
@leex279 @zeneiltongpdev Thanks for your help, both of you.

I did a workaround for the Brave issue by creating a simple CLI tool called [armanossiloko/directory-watcher](https://github.com/armanossiloko/directory-watcher) which I define to monitor `bolt.diy` downloaded ZIPs and auto-extract them to my local repository in a specified directory. I will mark this as closed as this was not a `bolt.diy` issue in first place.

**Comment by zeneiltongpdev** [comment]
> [@leex279](https://github.com/leex279) [@zeneiltongpdev](https://github.com/zeneiltongpdev) Thanks for your help, both of you.
> 
> I did a workaround for the Brave issue by creating a simple CLI tool called [armanossiloko/directory-watcher](https://github.com/armanossiloko/directory-watcher) which I define to monitor `bolt.diy` downloaded ZIPs and auto-extract them to my local repository in a specified directory. I will mark this as closed as this was not a `bolt.diy` issue in first place.

@armanossiloko Ok bro, thanks for letting us know, great work for you ⚡

**Comment by colossatr0n** [comment]
For anyone else coming here, Brave responded to @armanossiloko's inquiry about the Files System API access: 

The flag that controls this is `brave://flags/#file-system-access-api`
